Reading training file
Finished reading files and dropping unnamed column, took: 104.03680491447449
Defined classifier
Fitting the grid
Fitting 4 folds for each of 24 candidates, totalling 96 fits
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:   26.4s
[Parallel(n_jobs=2)]: Done   2 tasks      | elapsed:   26.5s
[Parallel(n_jobs=2)]: Done   3 tasks      | elapsed:   26.5s
[Parallel(n_jobs=2)]: Done   4 tasks      | elapsed:   26.5s
Traceback (most recent call last):
  File "gridsearch.py", line 91, in <module>
    grid.fit(train.drop("HasDetections", axis=1), train['HasDetections'])
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 722, in fit
    self._run_search(evaluate_candidates)
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1191, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 711, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/pianosaremusic/anaconda3/envs/ml/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
sklearn.externals.joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}
